name: todo

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  # STATE MANAGEMENT
  flutter_riverpod: ^2.6.1

  # ROUTING
  go_router: ^16.0.0

  # FIREBASE
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0

  # SQFLITE
  sqflite: ^2.4.2
  path: ^1.9.1
  sqflite_common_ffi: ^2.3.3

  # UUID
  uuid: ^4.5.1

  # BUILT VALUE
  built_value: ^8.9.2
  built_collection: ^5.1.1

  # ICONS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # CODE GENERATION
  build_runner: ^2.4.8
  built_value_generator: ^8.9.2

flutter:
  uses-material-design: true