// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHVfb6ymvmyVyN13sM5rZlNn9IPSuEVwk',
    appId: '1:82782886346:web:00c43110bf7f3b0a285733',
    messagingSenderId: '82782886346',
    projectId: 'todo-app-f9f22',
    authDomain: 'todo-app-f9f22.firebaseapp.com',
    storageBucket: 'todo-app-f9f22.firebasestorage.app',
    measurementId: 'G-FFBG0YV05G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDad-xR5YAveujhEl3InNL3xYhmNESEoLA',
    appId: '1:82782886346:android:1a98373d210b1734285733',
    messagingSenderId: '82782886346',
    projectId: 'todo-app-f9f22',
    storageBucket: 'todo-app-f9f22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1p3eTbeRmz1qMEd6SxW5Y_8AEvZVp0G0',
    appId: '1:82782886346:ios:362bf6a46d61da04285733',
    messagingSenderId: '82782886346',
    projectId: 'todo-app-f9f22',
    storageBucket: 'todo-app-f9f22.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1p3eTbeRmz1qMEd6SxW5Y_8AEvZVp0G0',
    appId: '1:82782886346:ios:362bf6a46d61da04285733',
    messagingSenderId: '82782886346',
    projectId: 'todo-app-f9f22',
    storageBucket: 'todo-app-f9f22.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHVfb6ymvmyVyN13sM5rZlNn9IPSuEVwk',
    appId: '1:82782886346:web:f93f2e9f9420f37a285733',
    messagingSenderId: '82782886346',
    projectId: 'todo-app-f9f22',
    authDomain: 'todo-app-f9f22.firebaseapp.com',
    storageBucket: 'todo-app-f9f22.firebasestorage.app',
    measurementId: 'G-ZZJCL3DEMW',
  );

}